error_log2: OK
